name: tunele-api-local

services:
  api:
    image: tunele-api-local
    container_name: tunele-api-local
    env_file: "../.env"
    environment:
      - REDIS_URL=redis://redis:6379
    build:
      context: ../../../ # Pull the yarn.lock from the root directory
      dockerfile: ./src/backend/docker/Dockerfile
    ports:
      - "7600:7600"
    restart: unless-stopped
    networks:
      - tunele-network
    volumes:
      - ../logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7600/api/health"]
      interval: 5s
      timeout: 10s
      retries: 5

  redis:
    image: redis:8-alpine
    container_name: tunele-redis
    restart: unless-stopped
    ports:
      - "6379:6379" # Expose Redis on port 6379 for development
    env_file: "../.env"
    networks:
      - tunele-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5

  grafana-agent:
    image: grafana/agent:latest
    container_name: tunele-grafana-agent-local
    restart: unless-stopped
    volumes:
      - ../grafana/grafana-agent.yml:/etc/agent/agent.yaml:ro
    environment:
      - CLUSTER_NAME=${CLUSTER_NAME}
      - API_HOST=api
      - API_PORT=7600
      - METRICS_AUTH_TOKEN=${METRICS_AUTH_TOKEN}
      - GRAFANA_CLOUD_PROMETHEUS_URL=${GRAFANA_PROMETHEUS_URL}
      - GRAFANA_CLOUD_PROMETHEUS_USERNAME=${GRAFANA_PROMETHEUS_USER}
      - GRAFANA_CLOUD_API_KEY=${GRAFANA_PROMETHEUS_TOKEN}
    command: ["-config.file=/etc/agent/agent.yaml", "-config.expand-env"]
    depends_on:
      api:
        condition: service_healthy
    networks:
      - tunele-network

networks:
  tunele-network:
    driver: bridge
